### ISSUE TITLE
`window.monitorInit` is not a function

### ISSUE THREAD

**Issue by susuhahnml** [runtime-monitoring/explanator2#1]
Hi! I was able to compile the system and use it n the shell. When I run the interactive page, `npm start` I get the page but when I click on the monitor button I get an error "Something bad happened. Please re-check your formula/trace and try again." 

No logs in the terminal but the web console shows this message bellow.

```
explanator2.bc.js:1 Uncaught SyntaxError: Unexpected token '<'
Monitor.js:40 TypeError: window.monitorInit is not a function
    at initMonitor (Monitor.js:20:1)
    at monitorStateReducer (Monitor.js:104:1)
    at dispatchAction (react-dom.development.js:16107:1)
    at handleMonitor (Monitor.js:183:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
```

Any idea how to fix it?

**Comment by leonardolima** [comment]
Hi, Susana. Thanks for your interest in this project.

In order to properly start the server locally, you should first copy the JavaScript library generated by Js_of_ocaml, i.e., after `$ dune build`, you should execute the following command from the root folder:

`$ cp js/explanator2.bc.js vis/public`

Sometimes you need to add the prefix "explanator2/" to the path of this file in `vis/public/index.html`. Specifically, in

`<script
    src="explanator2.bc.js"
    type="text/javascript">
</script>`

`explanator2.bc.js` should be replaced with `explanator2/explanator2.bc.js`. This happens because of the way I set up the project with GitHub pages, but I will fix it in the near future.

Just to give you a heads up: we are going to release a new version of this project soon (in around a month or two). There is a lot of work in the branches `formalization` and `visualization` that will be pushed to the main branch. We essentially extended the specification language with the first-order fragment (i.e., predicates and quantifiers).

I apologize for the lack of documentation. This is one of my priorities in the next release.

Please don't hesitate to ask more questions.

Best wishes,
Leonardo
